name: Auto Build dsh Docker Image

on:
  schedule:
    - cron: '0 19 * * *' # 每天凌晨 3 点自动检查更新
  workflow_dispatch:      # 允许手动触发

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get latest dsh version from npm
        id: dsh_version
        run: |
          npm config set registry https://registry.npmmirror.com
          VERSION=$(npm view @deepseek-ai/dsh version)
          echo "DSH_VERSION=$VERSION" >> $GITHUB_ENV
          echo "Latest dsh version is $VERSION"

      - name: Set lowercase image name
        run: |
          echo "IMAGE_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ env.IMAGE_NAME }}:latest
            ghcr.io/${{ env.IMAGE_NAME }}:${{ env.DSH_VERSION }}
          build-args: |
            DSH_VERSION=${{ env.DSH_VERSION }}
